SafeChest/Models/ErrorViewModel.cs
namespace SafeChest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SafeChest/Models/HouseHoldGoods.cs
namespace SafeChest.Models
{
    public class HouseHoldGoods
    {
        public int Id { get; set; }
        public string Item { get; set; }
        public int Value { get; set; }
        public string Image { get; set; }
        public DateTime DatePurchased { get; set; }


        public HouseHoldGoods()
        {
            
        }
    }
}

SafeChest/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SafeChest.Models;
using System.Diagnostics;

namespace SafeChest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SafeChest/Controllers/HouseHoldGoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SafeChest.Data;
using SafeChest.Models;

namespace SafeChest.Controllers
{
    public class HouseHoldGoodsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HouseHoldGoodsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: HouseHoldGoods
        public async Task<IActionResult> Index()
        {
            return View(await _context.HouseHoldGoods.ToListAsync());
        }

        // GET: HouseHoldGoods/ShowSearchForm()
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // PoST: HouseHoldGoods/ShowSearchForm()
        public async Task<IActionResult> ShowSearchResults(String ItemName)
        {
            return View("Index", await _context.HouseHoldGoods.Where(j => j.Item.Contains(ItemName)).ToListAsync());
        }

        // GET: HouseHoldGoods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var houseHoldGoods = await _context.HouseHoldGoods
                .FirstOrDefaultAsync(m => m.Id == id);
            if (houseHoldGoods == null)
            {
                return NotFound();
            }

            return View(houseHoldGoods);
        }

        // GET: HouseHoldGoods/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: HouseHoldGoods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Item,Value,Image,DatePurchased")] HouseHoldGoods houseHoldGoods)
        {
            if (ModelState.IsValid)
            {
                _context.Add(houseHoldGoods);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(houseHoldGoods);
        }

        // GET: HouseHoldGoods/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var houseHoldGoods = await _context.HouseHoldGoods.FindAsync(id);
            if (houseHoldGoods == null)
            {
                return NotFound();
            }
            return View(houseHoldGoods);
        }

        // POST: HouseHoldGoods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Item,Value,Image,DatePurchased")] HouseHoldGoods houseHoldGoods)
        {
            if (id != houseHoldGoods.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(houseHoldGoods);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HouseHoldGoodsExists(houseHoldGoods.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(houseHoldGoods);
        }

        // GET: HouseHoldGoods/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var houseHoldGoods = await _context.HouseHoldGoods
                .FirstOrDefaultAsync(m => m.Id == id);
            if (houseHoldGoods == null)
            {
                return NotFound();
            }

            return View(houseHoldGoods);
        }

        // POST: HouseHoldGoods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var houseHoldGoods = await _context.HouseHoldGoods.FindAsync(id);
            if (houseHoldGoods != null)
            {
                _context.HouseHoldGoods.Remove(houseHoldGoods);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HouseHoldGoodsExists(int id)
        {
            return _context.HouseHoldGoods.Any(e => e.Id == id);
        }
    }
}

SafeChest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Safely store your belongings</a>.</p>
</div>

SafeChest/Views/HouseHoldGoods/Create.cshtml
@model SafeChest.Models.HouseHoldGoods

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>HouseHoldGoods</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Item" class="control-label"></label>
                <input asp-for="Item" class="form-control" />
                <span asp-validation-for="Item" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePurchased" class="control-label"></label>
                <input asp-for="DatePurchased" class="form-control" />
                <span asp-validation-for="DatePurchased" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SafeChest/Views/HouseHoldGoods/Delete.cshtml
@model SafeChest.Models.HouseHoldGoods

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HouseHoldGoods</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Value)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatePurchased)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatePurchased)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SafeChest/Views/HouseHoldGoods/Details.cshtml
@model SafeChest.Models.HouseHoldGoods
@{
    ViewData["Title"] = "Details";
}
<h1>Details</h1>
<div>
    <h4>HouseHoldGoods</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Value)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatePurchased)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatePurchased)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SafeChest/Views/HouseHoldGoods/Edit.cshtml
@model SafeChest.Models.HouseHoldGoods

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>HouseHoldGoods</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Item" class="control-label"></label>
                <input asp-for="Item" class="form-control" />
                <span asp-validation-for="Item" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePurchased" class="control-label"></label>
                <input asp-for="DatePurchased" class="form-control" />
                <span asp-validation-for="DatePurchased" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SafeChest/Views/HouseHoldGoods/Index.cshtml
@model IEnumerable<SafeChest.Models.HouseHoldGoods>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Item)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SafeChest/Views/HouseHoldGoods/ShowSearchForm.cshtml
<h4>Search for your homegoods</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name ="ItemName" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SafeChest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SafeChest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SafeChest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SafeChest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HouseHoldGoods" asp-action="Index">Chest</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HouseHoldGoods" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SafeChest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>